
require 'NOS:globals.mobile_effects.nos.applypoison'
require 'NOS:globals.mobile_effects.nos.beingcalmed'
require 'NOS:globals.mobile_effects.nos.beingprovoked'
require 'NOS:globals.mobile_effects.nos.crookcalm'
require 'NOS:globals.mobile_effects.nos.crookprovoke'
require 'NOS:globals.mobile_effects.nos.criminal'
require 'NOS:globals.mobile_effects.nos.chaotic'
require 'NOS:globals.mobile_effects.nos.dig'
require 'NOS:globals.mobile_effects.nos.imbueweapon'
require 'NOS:globals.mobile_effects.nos.mentor'
require 'NOS:globals.mobile_effects.nos.mentoring'
require 'NOS:globals.mobile_effects.nos.murderer'
require 'NOS:globals.mobile_effects.nos.beingmentored'
require 'NOS:globals.mobile_effects.nos.taunt'
require 'NOS:globals.mobile_effects.nos.beingtaunted'

require 'NOS:globals.mobile_effects.nos.colorwarplayer'

require 'NOS:globals.mobile_effects.nos.archheal'
require 'NOS:globals.mobile_effects.nos.beingarchhealed'
require 'NOS:globals.mobile_effects.nos.masscurse'
require 'NOS:globals.mobile_effects.nos.archcure'
require 'NOS:globals.mobile_effects.nos.archprotection'
require 'NOS:globals.mobile_effects.nos.chainlightning'
require 'NOS:globals.mobile_effects.nos.chainlightninghit'
require 'NOS:globals.mobile_effects.nos.magiclock'
require 'NOS:globals.mobile_effects.nos.magicunlock'
require 'NOS:globals.mobile_effects.nos.magictrap'
require 'NOS:globals.mobile_effects.nos.magicuntrap'
require 'NOS:globals.mobile_effects.nos.summoncreature'
require 'NOS:globals.mobile_effects.nos.summondaemon'
require 'NOS:globals.mobile_effects.nos.traptriggered'

require 'NOS:globals.mobile_effects.nos.identify'
require 'NOS:globals.mobile_effects.nos.paralyze'
require 'NOS:globals.mobile_effects.nos.poison'
require 'NOS:globals.mobile_effects.nos.powerhour'
require 'NOS:globals.mobile_effects.nos.reclaim'
require 'NOS:globals.mobile_effects.nos.repair'
require 'NOS:globals.mobile_effects.nos.reveal'
require 'NOS:globals.mobile_effects.nos.revealed'
require 'NOS:globals.mobile_effects.nos.spiritspeak'
require 'NOS:globals.mobile_effects.nos.telecrookmove'

require 'NOS:globals.mobile_effects.buffs.spells.stonewall'
require 'NOS:globals.mobile_effects.buffs.spells.spellpoison'
require 'NOS:globals.mobile_effects.buffs.spells.spellcure'
require 'NOS:globals.mobile_effects.buffs.spells.spellmagicreflection'

require 'NOS:globals.mobile_effects.skills.pets.tame'

require 'NOS:globals.mobile_effects.potions.cure'
require 'NOS:globals.mobile_effects.potions.heal'
require 'NOS:globals.mobile_effects.potions.stamina'
require 'NOS:globals.mobile_effects.potions.mana'

require 'NOS:globals.mobile_effects.mounts.nomount'
require 'NOS:globals.mobile_effects.mounts.dismiss'