require 'globals.mobile_effects.nos.telecrookmove'
require 'globals.mobile_effects.nos.powerhour'
require 'globals.mobile_effects.nos.murderer'
require 'globals.mobile_effects.nos.crookcalm'
require 'globals.mobile_effects.nos.beingcalmed'
require 'globals.mobile_effects.nos.crookprovoke'
require 'globals.mobile_effects.nos.beingprovoked'