
require 'globals.mobile_effects.nos.applypoison'
require 'globals.mobile_effects.nos.beingcalmed'
require 'globals.mobile_effects.nos.beingprovoked'
require 'globals.mobile_effects.nos.crookcalm'
require 'globals.mobile_effects.nos.crookprovoke'
require 'globals.mobile_effects.nos.murderer'
require 'globals.mobile_effects.nos.criminal'
require 'globals.mobile_effects.nos.chaotic'
require 'globals.mobile_effects.nos.mentor'
require 'globals.mobile_effects.nos.beingmentored'

require 'globals.mobile_effects.nos.paralyze'
require 'globals.mobile_effects.nos.poison'
require 'globals.mobile_effects.nos.powerhour'
require 'globals.mobile_effects.nos.reclaim'
require 'globals.mobile_effects.nos.repair'
require 'globals.mobile_effects.nos.reveal'
require 'globals.mobile_effects.nos.revealed'
require 'globals.mobile_effects.nos.spiritspeak'
require 'globals.mobile_effects.nos.telecrookmove'

require 'globals.mobile_effects.buffs.spells.stonewall'
require 'globals.mobile_effects.buffs.spells.spellpoison'
require 'globals.mobile_effects.buffs.spells.spellcure'
require 'globals.mobile_effects.buffs.spells.spellmagicreflection'

require 'globals.mobile_effects.skills.pets.tame'

require 'globals.mobile_effects.potions.cure'
require 'globals.mobile_effects.potions.heal'
require 'globals.mobile_effects.potions.stamina'
require 'globals.mobile_effects.potions.mana'
