RecipeCategories = {
	MetalsmithSkill = {
		{
			Name = "Resources",
			Subcategories = {
				{"Ingots","Ingots","Materials1"},
			},
		},	
		{
			Name = "Weapons",
			Subcategories = {
				{"Slashing","Slashing","Slashing"},
				{"Bashing","Bashing","Bashing"},
				{"Piercing","Piercing","Piercing"},
				{"Polearms","Polearms","Bones"},
			},
		},	
		{
			Name = "Armor",
			Subcategories = {
				{"Head",},
				{"Legs",},
				{"Torso",},
			},
		},
		{ 
			Name = "Tools",
			Subcategories = {
				{"Tools",},
				},
		},
	},
	HealingSkill = {
		{
			Name = "First Aid",
			Subcategories = {
				{"First Aid" ,"First Aid","SilkFabric"},
			},
		},
	},
	WoodsmithSkill = {
		{
			Name = "Resources",
			Subcategories = {
                {"Wood","Wood","Wood"},
            },
		},	
		{
			Name = "Weapons",
			Subcategories = {
				{"Bows","Bows","Ranged"},
				{"Shields","Shields","Shield"},
			},
		},	
		{
			Name = "Furnishings",
			Subcategories = {
				{"CraftingStations" ,"Crafting Stations"},
				{"TablesChairs" ,"Tables & Chairs"},
				{"DecorativeItems" ,"Decorative Items"},
				{"Lighting" ,},
				{"Storage" ,},
				{"FencesWalls" ,"Fences"},
				},
		},
		{
			Name = "Tools",
			Subcategories = {
				{"Tools",},
			},
		},	
	},
	AlchemySkill = {
		{
			Name = "Potions",
			Subcategories = {
				{"LesserPotions" ,"Lesser Potions","HealingPotions"},
				{"RegularPotions" ,"Regular Potions","HealingPotions"},
				{"GreaterPotions" ,"Greater Potions","HealingPotions"},
				{"SuperiorPotions" ,"Superior Potions","HealingPotions"},
				{"Remedies" ,"Remedies","Storage"},

			},
		},
	},
	FabricationSkill = {
		{
			Name = "Resources",
			Subcategories = {
				{"Cloth","Cloth","RoyalSilkFabric"},
				{"Leather","Leather","TannedLeather"},				
			},
		},	
		{
			Name = "Armor",
			Subcategories = {
				{"Head",},
				{"Legs",},
				{"Torso",},
			},
		},
		{
			Name = "Clothing",
			Subcategories = {
				{"Head",},
				{"Legs",},
				{"Torso",},				
			},
		},		
        {
			Name = "Items",
			Subcategories = {
				{"Tools","Tools","Tools"},
				{"Horse","Pet Gear","PetArmor"},
				{"Containers","Containers","Storage"}
			},
		},
	},
	InscriptionSkill = {
		{
			Name = "Scrolls",
			Subcategories = 
			{
				{"Scrolls" ,"Scrolls","Storage"},
			},
		},
		{
			Name = "Spellbooks",
			Subcategories = 
			{
				{"Spellbooks" ,"Spellbooks","Storage"},
			},
		},
		{
			Name = "Books",
			Subcategories = 
			{
				{"Books" ,"Books","Storage"},
			},
		},
		{	
			Name = "Staves",
			Subcategories = {
				{"Padded","Padded","Anvil1"},
				{"Rookie","Rookie","Anvil2"},
				{"Journeyman","Journeyman","Anvil3"},
				{"Expert","Expert","Anvil4"},
				{"Master","Master","Anvil5"},
			},
		},
	},
}

AllRecipes = {
	MetalsmithSkill = {
		--Materials
		Iron = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Iron",
			CraftingTemplateFile = "resource_iron",
			Description = "Iron that has been cast into an ingot, ready to be shaped into weapons, armor and tools.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Ingots",
			NeedRecipe = false,
			CanSalvage = false,
			Resources = {
				IronOre = 5,
			},
		},

		Copper = {
			MinLevelToCraft = 20,
			MaxLevelToGain = 45,
			DisplayName = "Copper",
			CraftingTemplateFile = "resource_copper",
			Description = "Copper that has been cast into an ingot, ready to be shaped into weapons and armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Ingots",
			NeedRecipe = false,
			CanSalvage = false,
			Resources = {
				CopperOre = 5,
			},
		},

		Gold = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Gold",
			CraftingTemplateFile = "resource_gold",
			Description = "Gold that has been cast into an ingot, ready to be shaped into weapons and armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Ingots",
			NeedRecipe = false,
			CanSalvage = false,
			Resources = {
				GoldOre = 5,
			},
		},

		Cobalt = {
			MinLevelToCraft = 60,
			MaxLevelToGain = 85,
			DisplayName = "Cobalt",
			CraftingTemplateFile = "resource_cobalt",
			Description = "Cobalt that has been cast into an ingot, ready to be shaped into weapons and armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Ingots",
			NeedRecipe = true,
			CanSalvage = false,
			Resources = {
				CobaltOre = 5,
			},
		},

		Obsidian = {
			MinLevelToCraft = 80,
			MaxLevelToGain = 105,
			DisplayName = "Obsidian",
			CraftingTemplateFile = "resource_obsidian",
			Description = "Obsidian that has been cast into an ingot, ready to be shaped into weapons and armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Ingots",
			NeedRecipe = true,
			CanSalvage = false,
			Resources = {
				ObsidianOre = 5,
			},
		},

		--Daggers
		Dagger = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Dagger",
			CraftingTemplateFile = "weapon_dagger",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Piercing",
			NeedRecipe = false,
			Resources = {
				Iron = { Iron = 1 },
				Gold = { Gold = 1 },
				Copper = { Copper = 1 },
				Cobalt = { Cobalt = 1 },
				Obsidian = { Obsidian = 1 },
			},
		},
		Kryss = {
			MinLevelToCraft = 5,
			MaxLevelToGain = 30,
			DisplayName = "Kryss",
			CraftingTemplateFile = "weapon_kryss",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Piercing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 1 },
				Gold = { Gold = 1 },
				Copper = { Copper = 1 },
				Cobalt = { Cobalt = 1 },
				Obsidian = { Obsidian = 1 },
			},
		},
		Poniard = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Poniard",
			CraftingTemplateFile = "weapon_poniard",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Piercing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 1 },
				Gold = { Gold = 1 },
				Copper = { Copper = 1 },
				Cobalt = { Cobalt = 1 },
				Obsidian = { Obsidian = 1 },
			},
		},

		BoneDagger = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Bone Dagger",
			CraftingTemplateFile = "weapon_bone_dagger",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Piercing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 1 },
				Gold = { Gold = 1 },
				Copper = { Copper = 1 },
				Cobalt = { Cobalt = 1 },
				Obsidian = { Obsidian = 1 },
			},
		},

		--Swords

		Longsword = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Longsword",
			CraftingTemplateFile = "weapon_longsword",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Slashing",
			NeedRecipe = false,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},

		Broadsword = {
			MinLevelToCraft = 20,
			MaxLevelToGain = 45,
			DisplayName = "Broadsword",
			CraftingTemplateFile = "weapon_broadsword",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Slashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},

		Saber = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Saber",
			CraftingTemplateFile = "weapon_saber",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Slashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},

		Katana = {
			MinLevelToCraft = 30,
			MaxLevelToGain = 55,
			DisplayName = "Katana",
			CraftingTemplateFile = "weapon_katana",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Slashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},

		--Blunts

		Mace = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Mace",
			CraftingTemplateFile = "weapon_mace",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bashing",
			NeedRecipe = false,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},
		Hammer = {
			MinLevelToCraft = 30,
			MaxLevelToGain = 55,
			DisplayName = "Hammer",
			CraftingTemplateFile = "weapon_hammer",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},
		
		Maul = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Maul",
			CraftingTemplateFile = "weapon_maul",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},

		WarMace = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "War Mace",
			CraftingTemplateFile = "weapon_war_mace",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},

		--2h Blunts
		Quarterstaff = {
			MinLevelToCraft = 45,
			MaxLevelToGain = 70,
			DisplayName = "Quarterstaff",
			CraftingTemplateFile = "weapon_quarterstaff",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bashing",
			NeedRecipe = false,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		Warhammer = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Warhammer",
			CraftingTemplateFile = "weapon_warhammer",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},

		--Poles
		Pitchfork = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Warfork",
			CraftingTemplateFile = "weapon_warfork",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Polearms",
			NeedRecipe = false,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		Voulge = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Voulge",
			CraftingTemplateFile = "weapon_voulge",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Polearms",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		Spear = {
			MinLevelToCraft = 45,
			MaxLevelToGain = 70,
			DisplayName = "Spear",
			CraftingTemplateFile = "weapon_spear",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Polearms",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		Halberd = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Halberd",
			CraftingTemplateFile = "weapon_halberd",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Polearms",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},

		--2H Swords
		LargeAxe = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Large Axe",
			CraftingTemplateFile = "weapon_largeaxe",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Slashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		GreatAxe = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Great Axe",
			CraftingTemplateFile = "weapon_greataxe",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Slashing",
			NeedRecipe = true,
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		
		--Tool
		--Armor
		ChainHelm = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Chain Helm",
			CraftingTemplateFile = "armor_chain_helm",
			Description = "Chain Helms are very heavy armor pieces protecting a user's head. They absorb a massive amount of damage at the cost of agility.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = false,
			Category = "Armor",
			Subcategory = "Head",
			Resources = {
				Iron = { Iron = 1 },
				Gold = { Gold = 1 },
				Copper = { Copper = 1 },
				Cobalt = { Cobalt = 1 },
				Obsidian = { Obsidian = 1 },
			},
		},
		ChainLeggings = {
			MinLevelToCraft = 43,
			MaxLevelToGain = 68,
			DisplayName = "Chain Leggings",
			CraftingTemplateFile = "armor_chain_leggings",
			Description = "Chain Leggings are very heavy armor pieces protecting a user's head. They absorb a massive amount of damage at the cost of agility.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = false,
			Category = "Armor",
			Subcategory = "Legs",
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		ChainTunic = {
			MinLevelToCraft = 46,
			MaxLevelToGain = 71,
			DisplayName = "Chain Tunic",
			CraftingTemplateFile = "armor_chain_tunic",
			Description = "Chain Tunics are very heavy armor pieces protecting a user's torso.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = false,
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		ScaleHelm = {
			MinLevelToCraft = 49,
			MaxLevelToGain = 74,
			DisplayName = "Scale Helm",
			CraftingTemplateFile = "armor_scale_helm",
			Description = "Scale Helms are very heavy armor pieces protecting a user's head.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = true,
			Category = "Armor",
			Subcategory = "Head",
			Resources = {
				Iron = { Iron = 2 },
				Gold = { Gold = 2 },
				Copper = { Copper = 2 },
				Cobalt = { Cobalt = 2 },
				Obsidian = { Obsidian = 2 },
			},
		},
		ScaleLeggings = {
			MinLevelToCraft = 52,
			MaxLevelToGain = 77,
			DisplayName = "Scale Leggings",
			CraftingTemplateFile = "armor_scale_leggings",
			Description = "Scale leggings are very heavy armor pieces protecting a user's legs.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = true,
			Category = "Armor",
			Subcategory = "Legs",
			Resources = {
				Iron = { Iron = 4 },
				Gold = { Gold = 4 },
				Copper = { Copper = 4 },
				Cobalt = { Cobalt = 4 },
				Obsidian = { Obsidian = 4 },
			},
		},
		ScaleTunic = {
			MinLevelToCraft = 55,
			MaxLevelToGain = 80,
			DisplayName = "Scale Tunic",
			CraftingTemplateFile = "armor_scale_tunic",
			Description = "Scale tunics are very heavy armor pieces protecting a user's torso.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = true,
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {
				Iron = { Iron = 4 },
				Gold = { Gold = 4 },
				Copper = { Copper = 4 },
				Cobalt = { Cobalt = 4 },
				Obsidian = { Obsidian = 4 },
			},
		},
		FullPlateHelm = {
			MinLevelToCraft = 58,
			MaxLevelToGain = 83,
			DisplayName = "Full Plate Helm",
			CraftingTemplateFile = "armor_fullplate_helm",
			Description = "Full plate helms are very heavy armor pieces protecting a user's head.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = true,
			Category = "Armor",
			Subcategory = "Head",
			Resources = {
				Iron = { Iron = 3 },
				Gold = { Gold = 3 },
				Copper = { Copper = 3 },
				Cobalt = { Cobalt = 3 },
				Obsidian = { Obsidian = 3 },
			},
		},
		FullPlateLeggings = {
			MinLevelToCraft = 61,
			MaxLevelToGain = 86,
			DisplayName = "Full Plate Leggings",
			CraftingTemplateFile = "armor_fullplate_leggings",
			Description = "Full plate leggings are very heavy armor pieces protecting a user's legs.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = true,
			Category = "Armor",
			Subcategory = "Legs",
			Resources = {
				Iron = { Iron = 5 },
				Gold = { Gold = 5 },
				Copper = { Copper = 5 },
				Cobalt = { Cobalt = 5 },
				Obsidian = { Obsidian = 5 },
			},
		},
		FullPlateTunic = {
			MinLevelToCraft = 64,
			MaxLevelToGain = 89,
			DisplayName = "Full Plate Tunic",
			CraftingTemplateFile = "armor_fullplate_tunic",
			Description = "Full plate tunics are very heavy armor pieces protecting a user's torso.",
			ItemType = "ArmorClass",
			CanImprove = true,
			NeedRecipe = true,
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {
				Iron = { Iron = 5 },
				Gold = { Gold = 5 },
				Copper = { Copper = 5 },
				Cobalt = { Cobalt = 5 },
				Obsidian = { Obsidian = 5 },
			},
		},
		
		CookingPot = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Cooking Pot",
			CraftingTemplateFile = "tool_cookingpot",
			ItemType = "CraftingToolClass",
			Description = "A tool used for cooking food. Can create different more satisfying forms of food.",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Iron = 1,
			},
		},		
		
		MiningPick = {
			MinLevelToCraft = 5,
			MaxLevelToGain = 30,
			DisplayName = "Mining Pick",
			CraftingTemplateFile = "tool_mining_pick",
			ItemType = "HarvestToolClass",
			Description = "A mining pick. Can be used to mine rocks for ores, minerals, gems. Can be used in combat.",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Iron = 1,
			},
		},

		Lockpick = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Lockpicks",
			Description = "Used to pick locks.",
			NeedRecipe = true,
			CraftingTemplateFile = "tool_lockpick",
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Iron = 1,
			},
		},
		
		Shovel = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Shovel",
			CraftingTemplateFile = "tool_shovel",
			ItemType = "HarvestToolClass",
			Description = "A tool used for digging. Can be used to uncover buried items.",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Iron = 1,
			},
		},
		
		HuntingKnife = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Hunting Knife",
			CraftingTemplateFile = "tool_hunting_knife",
			ItemType = "HarvestToolClass",
			Description = "A tool used for carving animal meats and hides.",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Iron = 1,
			},
		},	

		Hatchet = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Hatchet",
			CraftingTemplateFile = "tool_hatchet",
			Description = "A tool used for cutting down trees. Can be used in combat.",
			ItemType = "HarvestToolClass",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Iron = 1,
			},
		},

		EngravingTool = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Enrgaving Tool",
			CraftingTemplateFile = "tool_engraving",
			Description = "A engraving tool.",
			ItemType = "HarvestToolClass",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Iron = 1,
			},
		},
	},

WoodsmithSkill = {
		
		--resources
		Brick = {
			MinLevelToCraft = -10,
			MaxLevelToGain = 15,
			DisplayName = "Brick",
			CraftingTemplateFile = "resource_brick",
			Description = "Brick",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Wood",
			NeedRecipe = false,
			CanSalvage = false,
			Resources = {
				Stone = 5,
			},
		},

		Boards = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Wooden Boards",
			CraftingTemplateFile = "resource_boards",
			Description = "Wooden Boards",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Wood",
			NeedRecipe = false,
			CanSalvage = false,
			Resources = {
				Wood = 5,
			},
		},

		AshBoards = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Ash Boards",
			CraftingTemplateFile = "resource_boards_ash",
			Description = "Ash Boards",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Wood",
			NeedRecipe = false,
			CanSalvage = false,
			Resources = {
				Ash = 5,
			},
		},

		BlightwoodBoards = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Blightwood Boards",
			CraftingTemplateFile = "resource_blightwood_boards",
			Description = "Blightwood Boards",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Wood",
			NeedRecipe = false,
			CanSalvage = false,
			Resources = {
				Blightwood = 5,
			},
		},
		--Bow
		ShortBow = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Short Bow",
			CraftingTemplateFile = "weapon_shortbow",
			ItemType = "WeaponClass",
			Description = "A Short Bow. This is a apprentice weapon.",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bows",
			NeedRecipe = false,
			Resources = {
				Boards = { Boards = 1 },
				AshBoards = { AshBoards = 1 },
				BlightwoodBoards = { BlightwoodBoards = 1 },
			},
		},
		LongBow = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Long Bow",
			CraftingTemplateFile = "weapon_longbow",
			ItemType = "WeaponClass",
			Description = "A Long Bow. This is a rookie weapon.",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bows",
			NeedRecipe = true,
			Resources = {
				Boards = { Boards = 2 },
				AshBoards = { AshBoards = 2 },
				BlightwoodBoards = { BlightwoodBoards = 2 },
			},
		},
		WarBow = {
			MinLevelToCraft = 65,
			MaxLevelToGain = 90,
			DisplayName = "War Bow",
			CraftingTemplateFile = "weapon_warbow",
			ItemType = "WeaponClass",
			Description = "A War Bow. This is a journeyman weapon.",
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Bows",
			NeedRecipe = true,
			Resources = {
				Boards = { Boards = 3 },
				AshBoards = { AshBoards = 3 },
				BlightwoodBoards = { BlightwoodBoards = 3 },
			},
		},
		--weapons

		Crook = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 75,
			DisplayName = "Crook",
			CraftingTemplateFile = "tool_crook",
			Description = "Used to tame animals.",
			ItemType = "WeaponClass",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Boards = 1,
			},
		},

		AshCrook = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 75,
			DisplayName = "Ashen Crook",
			CraftingTemplateFile = "tool_crook_ash",
			Description = "Used to tame and calm animals.",
			ItemType = "WeaponClass",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				AshBoards = 1,
				Iron = 1
			},
		},
		
		BlightCrook = {
			MinLevelToCraft = 60,
			MaxLevelToGain = 95,
			DisplayName = "Blighted Crook",
			CraftingTemplateFile = "tool_crook_blight",
			Description = "Used to calm and provoke monsters.",
			ItemType = "WeaponClass",
			NeedRecipe = false,
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				BlightwoodBoards = 1,
				Copper = 1
			},
		},
		
		Arrow = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Arrow",
			CraftingTemplateFile = "arrow",
			Description = "",
			NeedRecipe = false,
			CanImprove = false,
			Category = "Weapons",
			Subcategory = "Bows",
			StackCount = 20,
			Resources = {
				Boards = 1,
			},
		},

		AshArrow = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Ash Arrow",
			CraftingTemplateFile = "arrow_ash",
			Description = "",
			NeedRecipe = false,
			CanImprove = false,
			Category = "Weapons",
			Subcategory = "Bows",
			StackCount = 20,
			Resources = {
				AshBoards = 1,
				Feather = 1,
			},
		},

		BlightwoodArrow = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Blightwood Arrow",
			CraftingTemplateFile = "arrow_blightwood",
			Description = "",
			NeedRecipe = false,
			CanImprove = false,
			Category = "Weapons",
			Subcategory = "Bows",
			StackCount = 20,
			Resources = {
				BlightwoodBoards = 1,
				WildFeather = 1,
			},
		},

		--shields

		Buckler = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Buckler",
			CraftingTemplateFile = "shield_buckler",
			Description = "",
			ItemType = "WeaponClass",
			NeedRecipe = true,
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Shields",
			Resources = {
				Boards = { Boards = 1 },
				AshBoards = { AshBoards = 1 },
				BlightwoodBoards = { BlightwoodBoards = 1 },
			},
		},
		
		SmallShield = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Small Shield",
			CraftingTemplateFile = "shield_smallshield",
			Description = "",
			NeedRecipe = false,
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Shields",
			Resources = {
				Boards = { Boards = 1 },
				AshBoards = { AshBoards = 1 },
				BlightwoodBoards = { BlightwoodBoards = 1 },
			},
		},

		KiteShield = {
			MinLevelToCraft = 60,
			MaxLevelToGain = 85,
			DisplayName = "Kite Shield",
			CraftingTemplateFile = "shield_kite",
			Description = "",
			NeedRecipe = true,
			CanImprove = true,
			Category = "Weapons",
			Subcategory = "Shields",
			Resources = {
				Boards = { Boards = 2 },
				AshBoards = { AshBoards = 2 },
				BlightwoodBoards = { BlightwoodBoards = 2 },
			},
		},

		--furniture

		Barrel = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Barrel",
			Description = "A barrel made of wood.",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "barrel",
			Category = "Furnishings",
			Subcategory = "Storage",
			Resources = {
				Boards = 2,
			},
		},

		BedSmall = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Small Bed",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_bed_small",
			Description = "[$3130]",
			ItemType = "FurnitureClass",
			Category = "Furnishings",
			Subcategory = "DecorativeItems",
			Resources = {
				Boards = 20,
			},
		},

		BedLarge = {
			MinLevelToCraft = 60,
			MaxLevelToGain = 85,
			DisplayName = "Large Bed",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_bed_large",
			Description = "[$3131]",
			ItemType = "FurnitureClass",
			Category = "Furnishings",
			Subcategory = "DecorativeItems",
			Resources = {
				Boards = 50,
			},
		},
		BedMedium = {
			MinLevelToCraft = 55,
			MaxLevelToGain = 80,
			DisplayName = "Medium Bed",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_bed_medium",
			Description = "[$3132]",
			ItemType = "FurnitureClass",
			Category = "Furnishings",
			Subcategory = "DecorativeItems",
			Resources = {
				Boards = 40,
			},
		},
		BenchFancy = {
			MinLevelToCraft = 45,
			MaxLevelToGain = 70,
			DisplayName = "Fancy Bench",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_bench_fancy",
			Description = "[$3133]",
			Category = "Furnishings",
			Subcategory = "TablesChairs",
			Resources = {
				Boards = 4,
			},
		},
		BookshelfWooden = {
			MinLevelToCraft = 64,
			MaxLevelToGain = 89,
			DisplayName = "Wooden Bookshelf",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_bookshelf_wooden",
			Description = "[$3135]",
			Category = "Furnishings",
			Subcategory = "DecorativeItems",
			Resources = {
				Boards = 20,
			},
		},
		ChairFancy = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Fancy Chair",
			Description = "[$3138]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_chair_fancy",
			Category = "Furnishings",
			Subcategory = "TablesChairs",
			Resources = {
				Boards = 3,
			},
		},
		ChairWooden = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Wooden Chair",
			Description = "[$3139]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_chair_wooden",
			Category = "Furnishings",
			Subcategory = "TablesChairs",
			Resources = {
				Boards = 2,
			},
		},
		DeskFancy = {
			MinLevelToCraft = 70,
			MaxLevelToGain = 95,
			DisplayName = "Fancy Desk",
			ItemType = "FurnitureClass",
			Description = "[$3141]",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_desk_fancy",
			Category = "Furnishings",
			Subcategory = "TablesChairs",
			Resources = {
				Boards = 40,
			},
		},
		FireplaceStone = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Stone Fireplace",
			Description = "[$3142]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_fireplace_stone",
			Category = "Furnishings",
			Subcategory = "DecorativeItems",
			Resources = {
				Stone = 100,
			},
		},
		TableWooden = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Wooden Table",
			Description = "[$3143]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_table_wooden",
			Category = "Furnishings",
			Subcategory = "TablesChairs",
			Resources = {
				Boards = 4,
			},
		},
		TableWoodenLarge = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Large Wooden Table",
			Description = "[$3144]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_table_wooden_large",
			Category = "Furnishings",
			Subcategory = "TablesChairs",
			Resources = {
				Boards = 10,
			},
		},
		Shelf = {
			MinLevelToCraft = 20,
			MaxLevelToGain = 45,
			DisplayName = "Shelf",
			Description = "[$3146]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_shelf",
			Category = "Furnishings",
			Subcategory = "DecorativeItems",
			Resources = {
				Boards = 1,
			},
		},
		StoolWooden = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Wooden Stool",
			Description = "A small stool made of wood.",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_stool_wooden",
			Category = "Furnishings",
			Subcategory = "TablesChairs",
			Resources = {
				Boards = 1,
			},
		},
		Campfire = {
			MinLevelToCraft = -5,
			MaxLevelToGain = 20,
			DisplayName = "Campfire",
			Description = "[$3147]",
			ItemType = "FurnitureClass",
			NeedRecipe = false,
			CraftingTemplateFile = "campfire",
			Category = "Furnishings",
			Subcategory = "DecorativeItems",
			Resources = {
				Wood = 10,
			},
		},
		Crate = {
			MinLevelToCraft = 45,
			MaxLevelToGain = 70,
			DisplayName = "Crate",
			Description = "A basic wooden crate used to store belongings.",
			NeedRecipe = true,
			CraftingTemplateFile = "crate_empty",
			Category = "Furnishings",
			Subcategory = "Storage",
			Resources = {
				Boards = 2,
			},
		},
		Lockbox = {
			MinLevelToCraft = 55,
			MaxLevelToGain = 80,
			DisplayName = "Lockbox",
			Description = "A lockable secure container used to store belongings.",
			NeedRecipe = true,
			CraftingTemplateFile = "lockbox",
			Category = "Furnishings",
			Subcategory = "Storage",
			Resources = {
				Boards = 4,
			},
		},
		Dresser = {
			MinLevelToCraft = 60,
			MaxLevelToGain = 85,
			DisplayName = "Dresser",
			Description = "[$3148]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_dresser",
			Category = "Furnishings",
			Subcategory = "Storage",
			Resources = {
				Boards = 40,
			},
		},
		SmallFence = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Small Fence",
			Description = "[$3149]",
			NeedRecipe = true,
			CraftingTemplateFile = "fence_small",
			Category = "Furnishings",
			Subcategory = "FencesWalls",
			Resources = {
				Boards = 2,
			},
		},
		Gate = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Gate",
			Description = "",
			NeedRecipe = true,
			CraftingTemplateFile = "fence_door",
			Category = "Furnishings",
			Subcategory = "FencesWalls",
			Resources = {
				Boards = 4,
			},
		},
		Chest = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Chest",
			Description = "[$3151]",
			ItemType = "FurnitureClass",
			NeedRecipe = false,
			CraftingTemplateFile = "chest_secure",
			Category = "Furnishings",
			Subcategory = "Storage",
			Resources = {
				Boards = 4,
			},
		},
		WoodsmithTable = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Carpentry Table",
			Description = "[$3152]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "tool_carpentry_table",
			Category = "Furnishings",
			Subcategory = "CraftingStations",
			Resources = {
				Boards = 150,
			},
		},
		InscriptionTable = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Inscription Table",
			Description = "Used to create items using the inscription skill.",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "workbench_inscription",
			Category = "Furnishings",
			Subcategory = "CraftingStations",
			Resources = {
				Boards = 150,
			},
		},
		Loom = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Loom",
			Description = "[$3153]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "tool_loom",
			Category = "Furnishings",
			Subcategory = "CraftingStations",
			Resources = {
				Boards = 75,
			},
		},
		AlchemyTable = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Alchemy Table",
			Description = "[$3154]",
			ItemType = "FurnitureClass",
			NeedRecipe = true,
			CraftingTemplateFile = "workbench_alchemy",
			Category = "Furnishings",
			Subcategory = "CraftingStations",
			Resources = {
				Boards = 100,
			},
		},
		Torch = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Torch",
			Description = "[$3157]",
			NeedRecipe = false,
			CraftingTemplateFile = "torch",
			Category = "Furnishings",
			Subcategory = "Lighting",
			Resources = {
				Boards = 1,
			},
		},
		WallLantern = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Wall Lantern",
			Description = "",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_lantern_wall",
			Category = "Furnishings",
			Subcategory = "Lighting",
			Resources = {
				Boards = 2,
			},
		},
		HangingLantern = {
			MinLevelToCraft = 55,
			MaxLevelToGain = 80,
			DisplayName = "Hanging Lantern",
			Description = "",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_lantern_hanging",
			Category = "Furnishings",
			Subcategory = "Lighting",
			Resources = {
				Boards = 3,
			},
		},
		StandingTorch = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Standing Torch",
			Description = "",
			NeedRecipe = true,
			CraftingTemplateFile = "furniture_standingtorch",
			Category = "Furnishings",
			Subcategory = "Lighting",
			Resources = {
				Boards = 2,
			},
		},
		FishingRod = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Fishing Rod",
			ItemType = "HarvestToolClass",
			NeedRecipe = false,
			CraftingTemplateFile = "tool_fishing_rod",
			Description = "[$3161]",
			Category = "Tools",
			Subcategory = "Tools",
			Resources = {
				Boards = 1,
			},
		},	
		Anvil = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Anvil",
			NeedRecipe = true,
			CraftingTemplateFile = "tool_anvil",
			Description = "[$3163]",
			Category = "Furnishings",
			Subcategory = "CraftingStations",
			Resources = {
				Boards = 25,
				Iron = 100,
			},
		},
		Forge = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Forge",
			NeedRecipe = true,
			CraftingTemplateFile = "tool_forge_round",
			Description = "[$3162]",
			Category = "Furnishings",
			Subcategory = "CraftingStations",
			Resources = {
				Iron = 50,
				Stone = 100,
			},
		},
		Stove = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Stove",
			NeedRecipe = true,
			CraftingTemplateFile = "stove",
			Description = "[$3165]",
			Category = "Furnishings",
			Subcategory = "CraftingStations",
			Resources = {
				Iron = 50,
			},
		},
	},

FabricationSkill = {
		--Materials
		Cloth = {
            MinLevelToCraft = 0,
            MaxLevelToGain = 25,
            DisplayName = "Cloth",
            CraftingTemplateFile = "resource_bolt_of_cloth",
            Description = "A fabric woven from wool. Can be used to make clothing and armor.",
            ItemType = "ResourceClass",
            Category = "Resources",
            Subcategory = "Cloth",
            NeedRecipe = false,
            CanSalvage = false,
            StackCount = 5,
            Resources = {
                Cotton = 1,
            },
        },

		QuiltedCloth = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Quilted Cloth",
			CraftingTemplateFile = "resource_bolt_of_cloth_quilted",
			Description = "A fabric woven from fluffy wool. Can be used to make quilted clothing and armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Cloth",
			NeedRecipe = true,
			CanSalvage = false,
			StackCount = 5,
			Resources = {
				CottonFluffy = 1,
			},
		},

		SilkThread = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Silk Thread",
			CraftingTemplateFile = "animalparts_spider_silk",
			Description = "A fabric woven from fine silk. Can be used to make silk clothing and armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Cloth",
			NeedRecipe = false,
			CanSalvage = false,
			StackCount = 5,
			Resources = {
				Spidersilk = 5,
			},
		},

		SilkCloth = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Silk Cloth",
			CraftingTemplateFile = "resource_silk_cloth",
			Description = "A fabric woven from fine silk. Can be used to make silk clothing and armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Cloth",
			NeedRecipe = true,
			CanSalvage = false,
			StackCount = 5,
			Resources = {
				Silk = 1,
			},
		},

		Leather = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Leather",
			CraftingTemplateFile = "resource_leather",
			Description = "A material made from animal hides. Can be used to make leather armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Leather",
			NeedRecipe = false,
			CanSalvage = false,
			StackCount = 3,
			Resources = {
				LeatherHide = 1,
			},
		},

		BeastLeather = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Beast Leather",
			CraftingTemplateFile = "resource_beast_leather",
			Description = "A material made from beast hides. Can be used to make beast leather armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Leather",
			NeedRecipe = true,
			CanSalvage = false,
			StackCount = 3,
			Resources = {
				BeastLeatherHide = 1,
			},
		},

		VileLeather = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 100,
			DisplayName = "Vile Leather",
			CraftingTemplateFile = "resource_vile_leather",
			Description = "A material made from powerful vile beast hides. Can be used to make vile leather armor.",
			ItemType = "ResourceClass",
			Category = "Resources",
			Subcategory = "Leather",
			NeedRecipe = true,
			CanSalvage = false,
			StackCount = 3,
			Resources = {
				VileLeatherHide = 1,
			},
		},

		--Resources

		ShortSleeveShirt = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Short Sleeve Shirt",
			Description = "A short sleeved shirt that offers no armor protection.",
			NeedRecipe = false,
			CanImprove = false,
			CraftingTemplateFile = "clothing_short_sleeve_shirt_chest",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Torso",
			Resources = {	
				Cloth = 6,
			},
		},

		Waterskin = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Waterskin",
			Description = "Can be filled with water for refreshment and cooking.",
			NeedRecipe = false,
			CanImprove = false,
			CraftingTemplateFile = "waterskin",
			ItemType = "ResourceClass",
			Category = "Items",
			Subcategory = "Tools",
			Resources = {
				Leather = 1,
			},
		},

		LongSleeveShirt = {
			MinLevelToCraft = 5,
			MaxLevelToGain = 30,
			DisplayName = "Long Sleeve Shirt",
			Description = "A long sleeved shirt that offers no armor protection.",
			NeedRecipe = false,
			CanImprove = false,
			CraftingTemplateFile = "clothing_long_sleeve_shirt_chest",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Torso",
			Resources = {	
				Cloth = 6,
			},
		},

		Shorts = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Shorts",
			Description = "Simple shorts that offers no armor protection.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_shorts_legs",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Legs",
			Resources = {	
				Cloth = 4,
			},
		},

		Skirts = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Skirt",
			Description = "A skirt wearable by both men and women that offers no armor protection.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_skirt_legs",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Legs",
			Resources = {	
				Cloth = 3,
			},
		},

		Apron = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 40,
			DisplayName = "Apron",
			Description = "A basic apron that offers no armor protection. A must for culinary masters.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_apron_chest",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Legs",
			Resources = {	
				Cloth = 5,
			},
		},
		
		Cloak = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 60,
			DisplayName = "Cloak",
			Description = "A basic cloak that offers no armor protection. A must for adventurers.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_chest_cloak_basic",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Torso",
			Resources = {	
				Cloth = 7,
			},
		},

		Blacksmith = {
			MinLevelToCraft = 20,
			MaxLevelToGain = 45,
			DisplayName = "Blacksmith Tunic",
			Description = "A blacksmith tunic.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_chest_blacksmith",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Torso",
			Resources = {	
				Cloth = 8,
			},
		},

		Bandana = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Bandana",
			Description = "A basic bandana that offers no armor protection.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_bandana_helm",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Head",
			Resources = {	
				Cloth = 4,
			},
		},

		BanditHood = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Bandit Hood",
			Description = "A bandit hood that offers no armor protection.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_bandit_hood_helm",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Head",
			Resources = {	
				Cloth = 4,
			},
		},

		MageHat = {
			MinLevelToCraft = 30,
			MaxLevelToGain = 55,
			DisplayName = "Mage Hat",
			Description = "To act like a mage, you need to look like a mage.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "clothing_mage_hat_helm",
			ItemType = "ArmorClass",
			Category = "Clothing",
			Subcategory = "Head",
			Resources = {	
				Cloth = 6,
			},
		},


		PaddedHelm = {
			MinLevelToCraft = 40,
			MaxLevelToGain = 65,
			DisplayName = "Padded Helm",
			Description = "A Padded Helm is a robe armor piece protecting a user's head.",
			NeedRecipe = false,
			CanImprove = true,
			CraftingTemplateFile = "robe_padded_helm",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Head",
			Resources = {
				Cloth = { Cloth = 10 },
				QuiltedCloth = { QuiltedCloth = 10 },
				SilkCloth = { SilkCloth = 10 },
			},
		},

		PaddedLegs = {
			MinLevelToCraft = 43,
			MaxLevelToGain = 68,
			DisplayName = "Padded Legs",
			Description = "Padded Leggings are a robe armor piece protecting a user's lower body.",
			NeedRecipe = false,
			CanImprove = true,
			CraftingTemplateFile = "robe_padded_leggings",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Legs",
			Resources = {
				Cloth = { Cloth = 15 },
				QuiltedCloth = { QuiltedCloth = 15 },
				SilkCloth = { SilkCloth = 15 },
			},
		},

		PaddedChest = {
			MinLevelToCraft = 46,
			MaxLevelToGain = 71,
			DisplayName = "Padded Chest",
			Description = "A Padded Chest is a robe armor piece protecting a user's upper body.",
			NeedRecipe = false,
			CanImprove = true,
			CraftingTemplateFile = "robe_padded_tunic",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {
				Cloth = { Cloth = 15 },
				QuiltedCloth = { QuiltedCloth = 15 },
				SilkCloth = { SilkCloth = 15 },
			},
		},

		LinenHelm = {
			MinLevelToCraft = 49,
			MaxLevelToGain = 74,
			DisplayName = "Linen Helm",
			Description = "A Linen Helm is a robe armor piece protecting a user's head.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "robe_linen_helm",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Head",
			Resources = {
				Cloth = { Cloth = 10 },
				QuiltedCloth = { QuiltedCloth = 15 },
				SilkCloth = { SilkCloth = 15 },
			},
		},

		LinenLegs = {
			MinLevelToCraft = 52,
			MaxLevelToGain = 77,
			DisplayName = "Linen Legs",
			Description = "Linen Leggings are a robe armor piece protecting a user's lower body.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "robe_linen_leggings",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Legs",
			Resources = {
				Cloth = { Cloth = 15 },
				QuiltedCloth = { QuiltedCloth = 15 },
				SilkCloth = { SilkCloth = 15 },
			},
		},

		LinenChest = {
			MinLevelToCraft = 55,
			MaxLevelToGain = 80,
			DisplayName = "Linen Chest",
			Description = "A Linen Chest is a robe armor piece protecting a user's upper body.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "robe_linen_tunic",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {
				Cloth = { Cloth = 15 },
				QuiltedCloth = { QuiltedCloth = 15 },
				SilkCloth = { SilkCloth = 15 },
			},
		},

		MageRobes = {
			MinLevelToCraft = 65,
			MaxLevelToGain = 90,
			DisplayName = "Mage Robes",
			Description = "An elegant robe",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "robe_robe",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {	
				Cloth = { Cloth = 20 },
				QuiltedCloth = { QuiltedCloth = 20 },
				SilkCloth = { SilkCloth = 20 },
			},
		},

		LeatherHelm = {
			MinLevelToCraft = 58,
			MaxLevelToGain = 83,
			DisplayName = "Leather Helm",
			Description = "A Leather Helm is a light armor piece protecting a user's head.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "armor_leather_helm",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Head",
			Resources = {
				Leather = { Leather = 8 },
				BeastLeather = { BeastLeather = 8 },
				VileLeather = { VileLeather = 8 },
			},
		},

		LeatherLegs = {
			MinLevelToCraft = 61,
			MaxLevelToGain = 86,
			DisplayName = "Leather Legs",
			Description = "Leather Leggings are a light armor piece protecting a user's lower body.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "armor_leather_leggings",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Legs",
			Resources = {
				Leather = { Leather = 12 },
				BeastLeather = { BeastLeather = 12 },
				VileLeather = { VileLeather = 12 },
			},
		},

		LeatherChest = {
			MinLevelToCraft = 64,
			MaxLevelToGain = 89,
			DisplayName = "Leather Chest",
			Description = "A Leather Chest is a light armor piece protecting a user's upper body.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "armor_leather_chest",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {
				Leather = { Leather = 8 },
				BeastLeather = { BeastLeather = 12 },
				VileLeather = { VileLeather = 12 },
			},
		},

		HardenedHood = {
			MinLevelToCraft = 67,
			MaxLevelToGain = 92,
			DisplayName = "Hardened Helm",
			Description = "A Hardened Leather Helm is a light armor piece protecting a user's head.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "armor_hardened_helm",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Head",
			Resources = {
				Leather = { Leather = 8 },
				BeastLeather = { BeastLeather = 12 },
				VileLeather = { VileLeather = 12 },
			},
		},
		
		HardenedLeggings = {
			MinLevelToCraft = 70,
			MaxLevelToGain = 95,
			DisplayName = "Hardened Leggings",
			Description = "Leather Leggings are a light armor piece protecting a user's lower body.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "armor_hardened_leggings",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Legs",
			Resources = {
				Leather = { Leather = 12 },
				BeastLeather = { BeastLeather = 12 },
				VileLeather = { VileLeather = 12 },
			},
		},
		
		HardenedChest = {
			MinLevelToCraft = 73,
			MaxLevelToGain = 98,
			DisplayName = "Hardened Chest",
			Description = "A Leather Chest is a light armor piece protecting a user's upper body.",
			NeedRecipe = true,
			CanImprove = true,
			CraftingTemplateFile = "armor_hardened_chest",
			ItemType = "ArmorClass",
			Category = "Armor",
			Subcategory = "Torso",
			Resources = {
				Leather = { Leather = 12 },
				BeastLeather = { BeastLeather = 12 },
				VileLeather = { VileLeather = 12 },
			},
		},

		Saddlebags = {
			MinLevelToCraft = 60,
			MaxLevelToGain = 80,
			DisplayName = "Leather Saddlebags",
			Description = "Can be equipped on a horse to provide additional storage.",
			NeedRecipe = true,
			CanImprove = false,
			CraftingTemplateFile = "saddlebags_packed",
			ItemType = "ArmorClass",
			Category = "Items",
			Subcategory = "Horse",
			Resources = {
				Leather = 15,
			},
		},		

		Pouch = {
			MinLevelToCraft = 10,
			MaxLevelToGain = 35,
			DisplayName = "Pouch",
			Description = "A small leather pouch.",
			NeedRecipe = false,
			CanImprove = false,
			CraftingTemplateFile = "pouch",
			Category = "Items",
			Subcategory = "Containers",
			Resources = {
				Leather = 1,
			},
		},
	},

AlchemySkill = {
		-- HEALTH --
		LesserHealthPotion = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Lesser Heal Potion",
			NeedRecipe = false,
			Description = "A potion that restores a small amount of life.",
			CraftingTemplateFile = "lesser_health_potion",
			Category = "Potions",
			Subcategory = "LesserPotions",
			Resources = {
				Ginseng = 1
			},
		},
		RegularHealthPotion = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 50,
			DisplayName = "Heal Potion",
			NeedRecipe = false,
			Description = "A potion that restores a life.",
			CraftingTemplateFile = "regular_health_potion",
			Category = "Potions",
			Subcategory = "RegularPotions",
			Resources = {
				Ginseng = 3
			},
		},
		GreaterHealthPotion = {
			MinLevelToCraft = 50,
			MaxLevelToGain = 75,
			DisplayName = "Greater Heal Potion",
			NeedRecipe = false,
			Description = "A potion that restores a large amount of life.",
			CraftingTemplateFile = "greater_health_potion",
			Category = "Potions",
			Subcategory = "GreaterPotions",
			Resources = {
				Ginseng = 7
			},
		},
		SuperiorHealthPotion = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 85,
			DisplayName = "Superior Heal Potion",
			NeedRecipe = false,
			Description = "A potion that restores a huge amount of life.",
			CraftingTemplateFile = "superior_health_potion",
			Category = "Potions",
			Subcategory = "SuperiorPotions",
			Resources = {
				Ginseng = 12
			},
		},


		-- STAMINA --
		LesserStaminaPotion = {
			MinLevelToCraft = 8,
			MaxLevelToGain = 33,
			DisplayName = "Lesser Stamina Potion",
			NeedRecipe = false,
			Description = "A potion that restores a small amount of stamina. ",
			CraftingTemplateFile = "lesser_stamina_potion",
			Category = "Potions",
			Subcategory = "LesserPotions",
			Resources = {
				Blackpearl = 1
			},
		},
		RegularStaminaPotion = {
			MinLevelToCraft = 33,
			MaxLevelToGain = 58,
			DisplayName = "Stamina Potion",
			NeedRecipe = false,
			Description = "A potion that restores stamina. ",
			CraftingTemplateFile = "regular_stamina_potion",
			Category = "Potions",
			Subcategory = "RegularPotions",
			Resources = {
				Blackpearl = 3
			},
		},
		GreaterStaminaPotion = {
			MinLevelToCraft = 58,
			MaxLevelToGain = 83,
			DisplayName = "Greater Stamina Potion",
			NeedRecipe = false,
			Description = "A potion that restores a large amount of stamina. ",
			CraftingTemplateFile = "greater_stamina_potion",
			Category = "Potions",
			Subcategory = "GreaterPotions",
			Resources = {
				Blackpearl = 7
			},
		},
		SuperiorStaminaPotion = {
			MinLevelToCraft = 72,
			MaxLevelToGain = 92,
			DisplayName = "Superior Stamina Potion",
			NeedRecipe = false,
			Description = "A potion that restores a huge amount of stamina. ",
			CraftingTemplateFile = "superior_stamina_potion",
			Category = "Potions",
			Subcategory = "SuperiorPotions",
			Resources = {
				Blackpearl = 12
			},
		},
		

		-- MANA --
		LesserManaPotion = {
			MinLevelToCraft = 4,
			MaxLevelToGain = 29,
			DisplayName = "Lesser Mana Potion",
			NeedRecipe = false,
			Description = "A potion that restores a small amount of mana. ",
			CraftingTemplateFile = "lesser_mana_potion",
			Category = "Potions",
			Subcategory = "LesserPotions",
			Resources = {
				Mandrake = 1
			},
		},
		RegularManaPotion = {
			MinLevelToCraft = 29,
			MaxLevelToGain = 54,
			DisplayName = "Mana Potion",
			NeedRecipe = false,
			Description = "A potion that restores mana. ",
			CraftingTemplateFile = "regular_mana_potion",
			Category = "Potions",
			Subcategory = "RegularPotions",
			Resources = {
				Mandrake = 3
			},
		},
		GreaterManaPotion = {
			MinLevelToCraft = 54,
			MaxLevelToGain = 79,
			DisplayName = "Greater Mana Potion",
			NeedRecipe = false,
			Description = "A potion that restores a large amount of mana. ",
			CraftingTemplateFile = "greater_mana_potion",
			Category = "Potions",
			Subcategory = "GreaterPotions",
			Resources = {
				Mandrake = 7
			},
		},
		SuperiorManaPotion = {
			MinLevelToCraft = 78,
			MaxLevelToGain = 92,
			DisplayName = "Superior Mana Potion",
			NeedRecipe = false,
			Description = "A potion that restores a huge amount of mana. ",
			CraftingTemplateFile = "superior_mana_potion",
			Category = "Potions",
			Subcategory = "SuperiorPotions",
			Resources = {
				Mandrake = 12
			},
		},

		-- CURE --
		LesserCurePotion = {
			MinLevelToCraft = 4,
			MaxLevelToGain = 29,
			DisplayName = "Lesser Cure Potion",
			NeedRecipe = false,
			Description = "An antidote.",
			CraftingTemplateFile = "lesser_cure_potion",
			Category = "Potions",
			Subcategory = "LesserPotions",
			Resources = {
				Garlic = 1
			},
		},
		RegularCurePotion = {
			MinLevelToCraft = 29,
			MaxLevelToGain = 54,
			DisplayName = "Cure Potion",
			NeedRecipe = false,
			Description = "An antidote.",
			CraftingTemplateFile = "regular_cure_potion",
			Category = "Potions",
			Subcategory = "RegularPotions",
			Resources = {
				Garlic = 3
			},
		},
		GreaterCurePotion = {
			MinLevelToCraft = 54,
			MaxLevelToGain = 79,
			DisplayName = "Greater Cure Potion",
			NeedRecipe = false,
			Description = "An antidote.",
			CraftingTemplateFile = "greater_cure_potion",
			Category = "Potions",
			Subcategory = "GreaterPotions",
			Resources = {
				Garlic = 7
			},
		},
		SuperiorCurePotion = {
			MinLevelToCraft = 78,
			MaxLevelToGain = 92,
			DisplayName = "Superior Cure Potion",
			NeedRecipe = false,
			Description = "An antidote.",
			CraftingTemplateFile = "superior_cure_potion",
			Category = "Potions",
			Subcategory = "SuperiorPotions",
			Resources = {
				Garlic = 12
			},
		},

		-- CURE --
		LesserPoisonPotion = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 84,
			DisplayName = "Lesser Poison Potion",
			NeedRecipe = false,
			Description = "Poison!",
			CraftingTemplateFile = "lesser_poison_potion",
			Category = "Potions",
			Subcategory = "LesserPotions",
			Resources = {
				Nightshade = 1
			},
		},
		RegularPoisonPotion = {
			MinLevelToCraft = 82,
			MaxLevelToGain = 90,
			DisplayName = "Poison Potion",
			NeedRecipe = false,
			Description = "Poison!",
			CraftingTemplateFile = "regular_poison_potion",
			Category = "Potions",
			Subcategory = "RegularPotions",
			Resources = {
				Nightshade = 3
			},
		},
		GreaterPoisonPotion = {
			MinLevelToCraft = 89,
			MaxLevelToGain = 98,
			DisplayName = "Greater Poison Potion",
			NeedRecipe = false,
			Description = "Poison!",
			CraftingTemplateFile = "greater_poison_potion",
			Category = "Potions",
			Subcategory = "GreaterPotions",
			Resources = {
				Nightshade = 7
			},
		},
		SuperiorPoisonPotion = {
			MinLevelToCraft = 97,
			MaxLevelToGain = 100,
			DisplayName = "Superior Poison Potion",
			NeedRecipe = false,
			Description = "Poison!",
			CraftingTemplateFile = "superior_poison_potion",
			Category = "Potions",
			Subcategory = "SuperiorPotions",
			Resources = {
				Nightshade = 12
			},
		},


		-- DYES--
		--[[DyeYellow = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Yellow Dye",
			NeedRecipe = true,
			Description = "Yellow Dye. ",
			CraftingTemplateFile = "dye_yellow",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 1,
			},
		},
		DyeRed = {
			MinLevelToCraft = -15,
			MaxLevelToGain = 35,
			DisplayName = "Red Dye",
			NeedRecipe = true,
			Description = "Red Dye. ",
			CraftingTemplateFile = "dye_red",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 1,
			},
		},
		DyePurple = {
			MinLevelToCraft = -5,
			MaxLevelToGain = 45,
			DisplayName = "Purple Dye",
			NeedRecipe = true,
			Description = "Purple Dye. ",
			CraftingTemplateFile = "dye_purple",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 1,
			},
		},
		DyePink = {
			MinLevelToCraft = 5,
			MaxLevelToGain = 55,
			DisplayName = "Pink Dye",
			NeedRecipe = true,
			Description = "Pink Dye. ",
			CraftingTemplateFile = "dye_pink",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 3,
			},
		},
		DyeOrange = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 65,
			DisplayName = "Orange Dye",
			NeedRecipe = true,
			Description = "Orange Dye. ",
			CraftingTemplateFile = "dye_orange",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 3,
			},
		},
		DyeGrey = {
			MinLevelToCraft = 25,
			MaxLevelToGain = 75,
			DisplayName = "Grey Dye",
			NeedRecipe = true,
			Description = "Grey Dye. ",
			CraftingTemplateFile = "dye_grey",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 3,
			},
		},
		DyeGreen = {
			MinLevelToCraft = 35,
			MaxLevelToGain = 85,
			DisplayName = "Green Dye",
			NeedRecipe = true,
			Description = "Green Dye. ",
			CraftingTemplateFile = "dye_green",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 5,
			},
		},
		DyeBrown = {
			MinLevelToCraft = 45,
			MaxLevelToGain = 95,
			DisplayName = "Brown Dye",
			NeedRecipe = true,
			Description = "Brown Dye. ",
			CraftingTemplateFile = "dye_brown",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 5,
			},
		},
		DyeGold = {
			MinLevelToCraft = 55,
			MaxLevelToGain = 105,
			DisplayName = "Gold Dye",
			NeedRecipe = true,
			Description = "Gold Dye. ",
			CraftingTemplateFile = "dye_Gold",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 5,
			},
		},
		DyeBlue = {
			MinLevelToCraft = 65,
			MaxLevelToGain = 115,
			DisplayName = "Blue Dye",
			NeedRecipe = true,
			Description = "Blue Dye. ",
			CraftingTemplateFile = "dye_blue",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 5,
			},
		},
		DyeBlack = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Black Dye",
			NeedRecipe = true,
			Description = "Black Dye. ",
			CraftingTemplateFile = "dye_black",
			Category = "Potions",
			Subcategory = "Dye",
			Resources = {
				GiantMushrooms = 7,
			},
		},]]
	},

InscriptionSkill = {
		HealScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Heal Scroll",
			NeedRecipe = false,
			Description = "A heal scroll. ",
			CraftingTemplateFile = "lscroll_heal",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				BlankScroll = 1,
			},
		},
		RefreshScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Refresh Scroll",
			NeedRecipe = false,
			Description = "A refresh scroll. ",
			CraftingTemplateFile = "lscroll_refresh",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		InfuseScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Infuse Scroll",
			NeedRecipe = false,
			Description = "An Infuse scroll. ",
			CraftingTemplateFile = "lscroll_infuse",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		ManaMissileScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Magic Arrow Scroll",
			NeedRecipe = false,
			Description = "A Magic Arrow scroll. ",
			CraftingTemplateFile = "lscroll_mana_missile",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 1,
				BlankScroll = 1,
			},
		},
		StrengthScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Strength Scroll",
			NeedRecipe = false,
			Description = "An Strength scroll. ",
			CraftingTemplateFile = "scroll_strength",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		CunningScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Cunning Scroll",
			NeedRecipe = false,
			Description = "An Cunning scroll. ",
			CraftingTemplateFile = "scroll_cunning",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		ProtectionScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Protection Scroll",
			NeedRecipe = false,
			Description = "An Protection scroll. ",
			CraftingTemplateFile = "scroll_protection",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		AgileScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Agility Scroll",
			NeedRecipe = false,
			Description = "An Agility scroll. ",
			CraftingTemplateFile = "scroll_agile",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		FeeblemindScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Feeblemind Scroll",
			NeedRecipe = false,
			Description = "A Feeblemind scroll. ",
			CraftingTemplateFile = "scroll_feeblemind",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		WeakenScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Weaken Scroll",
			NeedRecipe = false,
			Description = "A Weaken scroll. ",
			CraftingTemplateFile = "scroll_weaken",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		ClumsyScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Clumsy Scroll",
			NeedRecipe = false,
			Description = "A Clumsy scroll. ",
			CraftingTemplateFile = "scroll_clumsy",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		CreateFoodScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Create Food Scroll",
			NeedRecipe = false,
			Description = "A Create Food scroll. ",
			CraftingTemplateFile = "scroll_create_food",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				FrayedScroll = 1,
			},
		},
		FireballScroll = {
			MinLevelToCraft = 3.5,
			MaxLevelToGain = 53.5,
			DisplayName = "Fireball Scroll",
			NeedRecipe = false,
			Description = "A Fireball scroll. ",
			CraftingTemplateFile = "lscroll_fireball",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 1,
				BlankScroll = 1,
			},
		},
		BlessScroll = {
			MinLevelToCraft = 3.5,
			MaxLevelToGain = 53.5,
			DisplayName = "Bless Scroll",
			NeedRecipe = false,
			Description = "A Bless scroll. ",
			CraftingTemplateFile = "scroll_bless",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 1,
				BlankScroll = 1,
			},
		},	
		CurseScroll = {
			MinLevelToCraft = 3.5,
			MaxLevelToGain = 53.5,
			DisplayName = "Curse Scroll",
			NeedRecipe = false,
			Description = "A Curse scroll. ",
			CraftingTemplateFile = "scroll_curse",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 1,
				BlankScroll = 1,
			},
		},
		--[[ReflectiveArmorcroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 50,
			DisplayName = "Repel Scroll",
			NeedRecipe = false,
			Description = "A repel scroll. ",
			CraftingTemplateFile = "lscroll_reflective_armor",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				BlankScroll = 1,
			},
		},]]
		CureScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 50,
			DisplayName = "Cure Scroll",
			NeedRecipe = false,
			Description = "A cure scroll. ",
			CraftingTemplateFile = "lscroll_cure",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 1,
				BlankScroll = 1,
			},
		},
		PoisonScroll = {
			MinLevelToCraft = 3.5,
			MaxLevelToGain = 53.5,
			DisplayName = "Poison Scroll",
			NeedRecipe = false,
			Description = "A Poison scroll. ",
			CraftingTemplateFile = "lscroll_poison",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Mushrooms = 1,
				FrayedScroll = 1,
			},
		},
		TeleportScroll = {
			MinLevelToCraft = 3.5,
			MaxLevelToGain = 53.5,
			DisplayName = "Teleport Scroll",
			NeedRecipe = false,
			Description = "A teleport scroll. ",
			CraftingTemplateFile = "lscroll_teleport",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 2,
				FrayedScroll = 1,
			},
		},
		RuinScroll = {
			MinLevelToCraft = -25,
			MaxLevelToGain = 25,
			DisplayName = "Ruin Scroll",
			NeedRecipe = false,
			Description = "A ruin scroll. ",
			CraftingTemplateFile = "lscroll_ruin",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 2,
				FrayedScroll = 1,
			},
		},
		LightningScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Lightning Scroll",
			NeedRecipe = false,
			Description = "A Lightning scroll. ",
			CraftingTemplateFile = "lscroll_lightning",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				FineScroll = 1,
			},
		},
		RecallScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Recall Scroll",
			NeedRecipe = false,
			Description = "A recall scroll. ",
			CraftingTemplateFile = "lscroll_recall",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				FineScroll = 1,
			},
		},
		EnergyWallScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Energy Field Scroll",
			NeedRecipe = false,
			Description = "A Energy Field scroll. ",
			CraftingTemplateFile = "scroll_energywall",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Mushrooms = 2,
				FineScroll = 1,
			},
		},
		FlameWaveScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Flame Wave Scroll",
			NeedRecipe = false,
			Description = "A Flame Wave scroll. ",
			CraftingTemplateFile = "scroll_flamewave",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Mushrooms = 2,
				FineScroll = 1,
			},
		},
		HailstormScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Ice Storm Scroll",
			NeedRecipe = false,
			Description = "A Ice Storm scroll. ",
			CraftingTemplateFile = "scroll_hailstorm",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Mushrooms = 2,
				FineScroll = 1,
			},
		},
		IcebladeScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Ice Blade Scroll",
			NeedRecipe = false,
			Description = "A Ice Blade scroll. ",
			CraftingTemplateFile = "scroll_iceblade",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Mushrooms = 2,
				FineScroll = 1,
			},
		},
		DefenseScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Defense Up Scroll",
			NeedRecipe = false,
			Description = "A Defense Up scroll. ",
			CraftingTemplateFile = "scroll_defense",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 2,
				FineScroll = 1,
			},
		},
		AttackScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Power Up Scroll",
			NeedRecipe = false,
			Description = "A Power Up scroll. ",
			CraftingTemplateFile = "scroll_attack",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 2,
				FineScroll = 1,
			},
		},
		GreaterHealScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Greater Heal Scroll",
			NeedRecipe = false,
			Description = "A Greater Heal scroll. ",
			CraftingTemplateFile = "lscroll_greater_heal",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 2,
				FineScroll = 1,
			},
		},
		MagicReflectionScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "MagicReflection Scroll",
			NeedRecipe = false,
			Description = "A Magic Reflection scroll. ",
			CraftingTemplateFile = "scroll_magicreflection",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 2,
				FineScroll = 1,
			},
		},
		PoisonFieldScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Poison Field Scroll",
			NeedRecipe = false,
			Description = "A Poison Field scroll. ",
			CraftingTemplateFile = "scroll_poisonfield",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 2,
				FineScroll = 1,
			},
		},
		StoneWallScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Stone Wall Scroll",
			NeedRecipe = false,
			Description = "A Stone Wall scroll. ",
			CraftingTemplateFile = "scroll_stonewall",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Ginseng = 2,
				FineScroll = 1,
			},
		},
		CloakScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Cloak Scroll",
			NeedRecipe = false,
			Description = "A cloak scroll. ",
			CraftingTemplateFile = "lscroll_cloak",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Mushrooms = 2,
				FineScroll = 1,
			},
		},
		NightsightScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Night Sight Scroll",
			NeedRecipe = false,
			Description = "A night sight scroll. ",
			CraftingTemplateFile = "scroll_nightsight",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Blackpearl = 2,
				FineScroll = 1,
			},
		},
		BombardmentScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Meteor Swarm Scroll",
			NeedRecipe = false,
			Description = "A Meteor Swarm scroll. ",
			CraftingTemplateFile = "lscroll_bombardment",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Mushrooms = 2,
				FineScroll = 1,
			},
		},
		EnergyBoltScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Energy Bolt Scroll",
			NeedRecipe = false,
			Description = "An energy bolt scroll.",
			CraftingTemplateFile = "lscroll_electricbolt",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				FineScroll = 1,
			},
		},
		RevealScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Reveal Scroll",
			NeedRecipe = false,
			Description = "An reveal scroll.",
			CraftingTemplateFile = "scroll_reveal",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				FineScroll = 1,
			},
		},
		ExplosionScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Explosion Scroll",
			NeedRecipe = false,
			Description = "An explosion scroll. ",
			CraftingTemplateFile = "scroll_explosion",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				FineScroll = 1,
			},
		},
		MindBlastScroll = {
			MinLevelToCraft = 46.4,
			MaxLevelToGain = 96.4,
			DisplayName = "Mind Blast Scroll",
			NeedRecipe = false,
			Description = "A mind blast scroll. ",
			CraftingTemplateFile = "scroll_mindblast",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				FineScroll = 1,
			},
		},
		MeteorScroll = {
			MinLevelToCraft = 60.7,
			MaxLevelToGain = 110.7,
			DisplayName = "Meteor Scroll",
			NeedRecipe = false,
			Description = "A meteor scroll. ",
			CraftingTemplateFile = "lscroll_meteor",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 2,
				AncientScroll = 1,
			},
		},
		ResurrectScroll = {
			MinLevelToCraft = 60.7,
			MaxLevelToGain = 110.7,
			DisplayName = "Resurrection Scroll",
			NeedRecipe = false,
			Description = "A resurrection scroll. ",
			CraftingTemplateFile = "lscroll_resurrect",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				AncientScroll = 1,
			},
		},
		AuraoffireScroll = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Flame Aura Scroll",
			NeedRecipe = false,
			Description = "A Flame Aura scroll. ",
			CraftingTemplateFile = "scroll_flameaura",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 2,
				AncientScroll = 1,
			},
		},
		EarthquakeScroll = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Earthquake Scroll",
			NeedRecipe = false,
			Description = "A earthquake scroll. ",
			CraftingTemplateFile = "lscroll_earthquake",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 2,
				AncientScroll = 1,
			},
		},
		WardEvilScroll = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Ward: Evil Scroll",
			NeedRecipe = false,
			Description = "A Ward: Evil scroll. ",
			CraftingTemplateFile = "lscroll_ward_evil",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 2,
				Ginseng = 2,
				AncientScroll = 1,
			},
		},
		WallOfFireScroll = {
			MinLevelToCraft = 17.8,
			MaxLevelToGain = 67.8,
			DisplayName = "Wall of Fire Scroll",
			NeedRecipe = false,
			Description = "A wall of fire scroll. ",
			CraftingTemplateFile = "lscroll_walloffire",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				LemonGrass = 2,
				FineScroll = 1,
			},
		},
		FlameStrikeScroll = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Flame Strike",
			NeedRecipe = false,
			Description = "A Flame Strike scroll. ",
			CraftingTemplateFile = "scroll_flamestrike",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				AncientScroll = 1,
			},
		},
		PortalScroll = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Portal Scroll",
			NeedRecipe = false,
			Description = "A portal scroll. ",
			CraftingTemplateFile = "lscroll_portal",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				AncientScroll = 1,
			},
		},
		Spellbook = {
			MinLevelToCraft = 15,
			MaxLevelToGain = 65,
			DisplayName = "Spellbook",
			NeedRecipe = false,
			CraftingTemplateFile = "spellbook",
			Description = "An empty spellbook. ",
			Category = "Spellbooks",
			Subcategory = "Spellbooks",
			Resources = {
				FrayedScroll = 10,
				FineScroll = 5,
				AncientScroll = 1,
			},
		},
		BookRed = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Book",
			NeedRecipe = false,
			CraftingTemplateFile = "book_red",
			Description = "An empty book. ",
			Category = "Books",
			Subcategory = "Books",
			Resources = {
				BlankScroll = 10,
			},
		},
		BookGreen = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Book",
			NeedRecipe = false,
			CraftingTemplateFile = "book_green",
			Description = "An empty book. ",
			Category = "Books",
			Subcategory = "Books",
			Resources = {
				BlankScroll = 10,
			},
		},
		BookBlue = {
			MinLevelToCraft = 0,
			MaxLevelToGain = 25,
			DisplayName = "Book",
			NeedRecipe = false,
			CraftingTemplateFile = "book_blue",
			Description = "An empty book. ",
			Category = "Books",
			Subcategory = "Books",
			Resources = {
				BlankScroll = 10,
			},
		},
		MarkScroll = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Mark Scroll",
			NeedRecipe = false,
			Description = "A mark scroll. ",
			CraftingTemplateFile = "lscroll_mark",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				AncientScroll = 1,
			},
		},
		FrostScroll = {
			MinLevelToCraft = 75,
			MaxLevelToGain = 125,
			DisplayName = "Frost Scroll",
			NeedRecipe = false,
			Description = "A frost scroll. ",
			CraftingTemplateFile = "lscroll_frost",
			Category = "Scrolls",
			Subcategory = "Scrolls",
			Resources = {
				Moss = 2,
				AncientScroll = 1,
			},
		},

		--weapons

		--[[ Staff = {
			MinLevelToCraft = 1,
			MaxLevelToGain = 51,
			DisplayName = "Staff",
			CraftingTemplateFile = "loa_staff_staff",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Staves",
			Subcategory = "Padded",
			NeedRecipe = false,
			Resources = {
				Boards = 5,
				LemonGrass = 5,
				Bones = 5,
			},
		},

		TribalStaff = {
			MinLevelToCraft = 24,
			MaxLevelToGain = 74,
			DisplayName = "Tribal Staff",
			CraftingTemplateFile = "loa_staff_tribal",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Staves",
			Subcategory = "Rookie",
			NeedRecipe = false,
			Resources = {
				Boards = 5,
				Mushrooms = 5,
				CursedBones = 5,
			},
		},

		JourneymanStaff = {
			MinLevelToCraft = 43,
			MaxLevelToGain = 93,
			DisplayName = "Journeyman Staff",
			CraftingTemplateFile = "loa_staff_journeyman",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Staves",
			Subcategory = "Journeyman",
			NeedRecipe = false,
			Resources = {
				BoardsDurable = 5,
				LemonGrass = 15,
				SpectralBones = 5,
			},
		},

		WhiteStaff = {
			MinLevelToCraft = 62,
			MaxLevelToGain = 112,
			DisplayName = "White Staff",
			CraftingTemplateFile = "loa_staff_white",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Staves",
			Subcategory = "Expert",
			NeedRecipe = false,
			Resources = {
				BlightwoodBoards = 5,
				Ginseng = 20,
				Miasma = 5,
			},
		},

		Redemption = {
			MinLevelToCraft = 70,
			MaxLevelToGain = 120,
			DisplayName = "Redemption",
			CraftingTemplateFile = "loa_staff_redemption",
			ItemType = "WeaponClass",
			CanImprove = true,
			Category = "Staves",
			Subcategory = "Master",
			NeedRecipe = false,
			Resources = {
				BlightwoodBoardsVile = 5,
				Moss = 40,
				MiasmaDeathly = 5,
			},
		},]]
	},
}