require 'NOS:globals.mobile_effects.general.generaleffect'
require 'NOS:globals.mobile_effects.general.adjuststamina'
require 'NOS:globals.mobile_effects.general.gatekeepereffect'
require 'NOS:globals.mobile_effects.general.atlas'
require 'NOS:globals.mobile_effects.general.map'
require 'NOS:globals.mobile_effects.general.rune'
require 'NOS:globals.mobile_effects.general.items'