require 'globals.mobile_effects.items.dye'
require 'globals.mobile_effects.items.arrows'
require 'globals.mobile_effects.items.bless'
require 'globals.mobile_effects.items.food'
require 'globals.mobile_effects.items.curse'
require 'globals.mobile_effects.items.land_deed'
require 'globals.mobile_effects.items.packed_object'
require 'globals.mobile_effects.items.house_blueprint'
require 'globals.mobile_effects.items.guild_charter'
require 'globals.mobile_effects.items.hearthstone'
require 'globals.mobile_effects.items.escapescroll'
require 'globals.mobile_effects.items.lotterybox'
require 'globals.mobile_effects.items.tax_credit'

require 'globals.mobile_effects.items.tools.hunting_knife'
require 'globals.mobile_effects.items.tools.lockpick'
require 'globals.mobile_effects.items.tools.cooking_pot'